project:
  type: website
  preview:
    port: 8800
    browser: false
  output-dir: docs
  # render:
  #   - index.qmd
    # - pages/*.ipynb
    # - pages/*.qmd
    # - slides/*.qmd

website:
  title: "AI-enhanced journal club"
  site-url: https://virtuelleakademie.github.io/ai-enhanced-journal-club
  repo-url: https://github.com/virtuelleakademie/ai-enhanced-journal-club
  navbar:
    left:
      - icon: card-list
        href: workshop/index.qmd
        text: Workshop
      - icon: info-circle
        href: prompting-llms/index.qmd
        text: Prompting recommendations
      - icon: file-slides
        text: "Slides" # {{< fa person-chalkboard >}}
        menu:
          - text: "How to read a paper"
            file: slides/index.qmd
      - icon: pen
        text: "Miro boards"
        menu:
          - text: "Morning session"
            file: miro-board/morning/index.qmd
          - text: "Afternoon session"
            file: miro-board/afternoon/index.qmd

  # sidebar:
  #   - title: "Workshop"
  #     style: "docked"
  #     search: true
  #     background: light
  #     contents:
  #       - workshop/index.qmd

page-footer:
    right:
    - icon: github
      href: https://github.com/virtuelleakademie/promptly-literate

format:
  html:
    theme:
      light: simplex
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
    # linkcolor: rebeccapurple
comments:
  hypothesis: 
    theme: clean
  # utterances: 
    # repo: virtuelleakademie/promptly-literate

execute:
  cache: true
  freeze: auto
  execute-dir: project

revealjs-plugins:
  - attribution
filters:
  - timer

editor:
  render-on-save: true

