project:
  type: website
  preview:
    port: 8800
    browser: false
  output-dir: docs
  # render:
  #   - index.qmd
    # - pages/*.ipynb
    # - pages/*.qmd
    # - slides/*.qmd

website:
  title: "AI-Enhanced Journal Club //"
  site-url: https://virtuelleakademie.github.io/promptly-educated
  repo-url: https://github.com/virtuelleakademie/promptly-educated
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: file-slides
        text: "Slides" # {{< fa person-chalkboard >}}
        menu:
          - text: "How to read a paper"
            file: slides/index.qmd
      
      - miro-board/index.qmd

page-footer:
    right:
    - icon: github
      href: https://github.com/virtuelleakademie/promptly-literate

format:
  html:
    theme:
      light: simplex
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
    # linkcolor: rebeccapurple
comments:
  hypothesis: 
    theme: clean
  # utterances: 
    # repo: virtuelleakademie/promptly-literate

execute:
  cache: true
  freeze: auto
  execute-dir: project



revealjs-plugins:
  - attribution
filters:
  - timer
